// Prove the widget tests catch the lifecycle mistakes that matter.
// Run:  node tests/mutate_widget.mjs      (exit status 1 if any mutant survives)
import { readFileSync, writeFileSync, mkdtempSync, copyFileSync, mkdirSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const widget = 'src/opnsense/www/js/widgets/TopDevices.js';
const source = readFileSync(join(root, widget), 'utf8');
const TESTS = ['tests/live_view.test.mjs', 'tests/netflow_ranges.test.mjs'];

const mutants = [
    ['stream URL not forgotten when leaving Live', '        this.eventSourceUrl = null;\n        this.eventSourceOnData = null;\n', ''],
    ['no guard against a range change during start-up', "        if (token !== this.live.token || this.state.range !== 'live') return;\n", ''],
    ['watchdog not cleared', '        if (this.live.watchdog) { clearInterval(this.live.watchdog); this.live.watchdog = null; }\n', ''],
    ['fixed timeouts instead of scaling with the interval', "    const eff = Math.max(1, effectiveS || 1) * 1000;", '    const eff = 1000;'],
    ['no automatic retry once unavailable', '            if (now - this.live.retryAt >= LIVE_RETRY_MS) this._startLive();\n', ''],
    ['a stale connect timer may reopen the stream outside Live', "        if (this.live.closed || this.state.range !== 'live') return;\n", ''],
    ['baseline events averaged in', '    if (!event || !(event.dt > 0)) return v;', '    if (!event) return v;'],
    ['picked devices vanish while idle', '        const ips = pick.length ? pick\n',
     '        const ips = pick.length ? Object.keys(rates)\n'],
    ['with nothing picked, Live is not seeded busiest first',
     '    return rows.sort((a, b) => (b.total - a.total) || ((seen[b.ip] || 0) - (seen[a.ip] || 0)) || byLabel(a, b));',
     '    return rows.sort(byLabel);'],
    ['filters ignored for picked devices', '    if (picked) return rows.sort(byLabel);',
     '    if (picked) return candidates.slice().sort(byLabel);'],
    ['a header click still sorts Live', "        if (this.state.range === 'live') return false;\n", ''],
    ['saved picks restored uncleaned', '        this.state.livePick = cleanPick(this.state.livePick);\n', ''],
    ['the picker offers the firewall itself', '            if (gateways[ip] || this._isBroadcast(ip)) continue;',
     '            if (this._isBroadcast(ip)) continue;'],
    ['a pick not seen today drops out of the picker', '...this.live.known, ...pick])) {', '...this.live.known])) {'],
    ['a renamed device is patched, not rebuilt', "    return rows.map(r => `${r.ip}|${r.name}|${r.net}`).join('\\n');",
     "    return rows.map(r => `${r.ip}|${r.net}`).join('\\n');"],
    ['every row re-sorted each update', '    if (!prev) {\n        order = ips.slice();', '    if (true) {\n        order = ips.slice();'],
    ['a selected device pushed off the bottom', '    if (n > 0 && at >= n) { order.splice(at, 1); order.splice(n - 1, 0, keep); }\n', ''],
    ['a new busiest does not push the bottom row off', '    return order.slice(0, n);\n}', '    return order;\n}'],
    ['a short list is not topped up', '        if (!order.includes(ip)) order.push(ip);', '        if (!order.includes(ip)) continue;'],
    ['the pointer does not hold the rows', 'if (!hold && top && top.total > 0 && order[0] !== top.ip) {',
     'if (top && top.total > 0 && order[0] !== top.ip) {'],
    ['an idle device moves to the top', 'if (!hold && top && top.total > 0 && order[0] !== top.ip) {',
     'if (!hold && top && order[0] !== top.ip) {'],
    ['the Live bar axis shrinks', '            this.live.yMax = Math.max(this.live.yMax, niceCeil(',
     '            this.live.yMax = Math.max(0, niceCeil('],
    ['a restart keeps the old axis top', '        this.live.yMax = 0;\n        this.live.dynOrder = null;\n',
     '        this.live.dynOrder = null;\n'],
    ['the axis top is not rounded', '    if (!(v > 0)) return 0;', '    return v;'],
    ['line colours follow the row, not the device',
     '            const c = l.colours[ip];\n            if (c && !taken.has(c)) { out[ip] = c; taken.add(c); }\n', ''],
    ['listed devices can share a line colour', 'LINE_COLOURS.find(c => !taken.has(c)) || LINE_COLOURS[0]',
     'LINE_COLOURS[Object.keys(l.colours).length % LINE_COLOURS.length]'],
    ['a line that just joined gets a quiet update', "this.chartObj.update(joined ? 'none' : 'quiet');",
     "this.chartObj.update('quiet');"],
    ["Dnsmasq's '*' shown as a name", " && l.hostname !== '*')", ')'],
    ['Down and Up swapped when patching a row', '                $td.eq(2).text(fmtRate(r.down));\n                $td.eq(3).text(fmtRate(r.up));\n',
     '                $td.eq(2).text(fmtRate(r.up));\n                $td.eq(3).text(fmtRate(r.down));\n'],
    ['rows rebuilt every interval instead of patched', 'if (rows.length && key === l.rowsKey && onScreen',
     'if (false && rows.length && key === l.rowsKey && onScreen'],
    ['the highlight not moved when patching', "                $(tr).toggleClass('info', this.state.selected === r.ip);\n", ''],
    ['a stale visit sizes the line axis', '                while (s.length && s[0].x < cutoff) s.shift();\n', ''],
    ['the line graph survives leaving Live', '        if (this.chartObj) { this.chartObj.destroy(); this.chartObj = null; }\n        $(\'.td-chartbox\').hide();\n',
     "        $('.td-chartbox').hide();\n"],
    ['a seen device on an unknown network cannot be picked', '            else if (pick.includes(ip) || this.live.known.has(ip)) other.devices.push(d);',
     '            else if (pick.includes(ip)) other.devices.push(d);'],
    ['switching the Live chart keeps the old axis top', '            if (kind !== this.state.liveChart) this.live.yMax = 0;', ''],
    ['the list seeded before the first measured interval', '            if (measured) l.dynOrder = order;\n',
     '            l.dynOrder = order;\n'],
    ['an idle device gets no line point',
     '        const ips = new Set([...Object.keys(devices), ...l.known, ...(this.state.livePick || []), ...l.order]);',
     '        const ips = new Set(Object.keys(devices));'],
    ["Live's chart choice lands on the NetFlow ranges", '            this.state.liveChart = kind;', '            this.state.chart = kind;'],
    ['three failed connects keep a shown tab from reconnecting',
     '        if (visible && this.eventSourceUrl !== null) this.eventSourceRetryCount = 0;\n', ''],
    ['quotes left unescaped in title attributes', ".html().replace(/\"/g, '&quot;'); }", '.html(); }'],
    ['the line graph offered outside Live', "            if (kind === 'line') return false;\n", ''],
    ['no stand-in without the streaming plugin', "        return kind === 'line' && !this._streamingOk() ? 'bar' : kind;",
     '        return kind;'],
    // NetFlow ranges
    ['all traffic read from the daily details, as before 0.1.2',
     '    for (const [res, kept] of TOTALS_KEPT) {', '    return detailsPlan(from, to, now);\n    for (const [res, kept] of TOTALS_KEPT) {'],
    ['no 5-minute or hourly buckets', 'const TOTALS_KEPT = [[300, 3600], [3600, DAY], [DAY, TOTALS_DAYS * DAY]];',
     'const TOTALS_KEPT = [[DAY, TOTALS_DAYS * DAY]];'],
    ['finer buckets used past their history', '        if (res === DAY || start >= Math.ceil((now - kept) / res) * res - res) {',
     '        if (true) {'],
    ['a bucket core may have dropped still counted', '    if (clipped) start = oldest;\n', ''],
    ['the details treated as kept forever', '    return planFor(DETAILS, DAY, DETAILS_DAYS * DAY, from, to, now);',
     '    return planFor(DETAILS, DAY, Infinity, from, to, now);'],
    ["internet only read from the totals, whose interface is the device's own side",
     "    if (scope === 'wan') return detailsPlan(from, to, now);\n", ''],
    ['window start rounded down, as the export does', '    const near = (t) => Math.round(t / res) * res;',
     '    const near = (t) => Math.floor(t / res) * res;'],
    ['a bucket still in progress claimed to its end', '    let end = to >= now ? now : Math.min(near(to), now);',
     '    let end = to >= now ? now : near(to);'],
    ['an empty span fetched anyway', '        if (plan.end <= plan.start) return [];\n', ''],
    ['totals rows read with the details convention', "        const sent = totals ? r.dir !== 'out' : r.dir === 'out';",
     "        const sent = r.dir === 'out';"],
    ['totals rows keyed on a destination they do not have', '        const ip = totals ? r.src : r.dst;',
     '        const ip = r.dst;'],
    ["an empty octets field read as NaN (core's extra column)", '                octets: parseFloat(c[ix.octets]) || 0',
     '                octets: parseFloat(c[ix.octets])'],
    ['the caption shows the window asked for', '        this.state.window = [plan.start, plan.end];',
     '        this.state.window = [from, to];'],
    ['the caption follows the scope control rather than the rows shown',
     "        const scopeTxt = q.scope === 'wan'", "        const scopeTxt = this.state.scope === 'wan'"],
    ['no note when the buckets are coarser than the range',
     '        if (p.res === DAY && (p.clipped || off >= Math.min(3600, (q.to - q.from) / 10))) {', '        if (false) {'],
    ['a note only when an hour off, however short the range', '        if (p.res === DAY && (p.clipped || off >= Math.min(3600, (q.to - q.from) / 10))) {',
     '        if (p.res === DAY && (p.clipped || off >= 3600)) {'],
    ['no word on a range cut to what is kept', "${p.clipped ? `, for ${days} days` : ''}", ''],
    ['an empty range shown without saying so', '        if (p.end <= p.start) {                  // nothing recorded, or nothing kept: say which',
     '        if (false) {'],
    ['days across a clock change said to start at one time', '            const starts = first === last ? first : `${first}, then ${last}`;',
     '            const starts = first;'],
    ['a multi-day span printed without its dates', '        if (day(a) === day(now) && day(b) === day(now)) return',
     '        if (true) return'],
    ['a span inside one minute printed as 10:00 → 10:00', '        const secs = day(a) === day(b) && this._hm(a) === this._hm(b);',
     '        const secs = false;'],
    ['Yesterday taken as 24 hours back', "            case 'yesterday': return [localMidnight(s, 1, this.tz), mid];",
     "            case 'yesterday': return [mid - DAY, mid];"],
    ['a scope change reloads nothing', '        while (this.state.window && q && q.scope !== this.state.scope) {',
     '        while (false) {'],
    ['a scope change reloads once, not until the rows match', '            q = this.state.request;\n        }',
     '            q = this.state.scope;\n        }'],
    ['a scope change reloads at a new moment', '            try { current = await this._load(q.now * 1000, this.state.scope); }',
     '            try { current = await this._load(Date.now(), this.state.scope); }'],
    ['a superseded load still lands', '        const flows = await this._export(plan);\n        if (token !== this._loadToken) return false;\n', '        const flows = await this._export(plan);\n'],
    ['a failed scope change keeps its rows', '            catch (e) { this._loadFailed(); return; }',
     '            catch (e) { /* keep previous rows */ }'],
    ['the cache keeps only the table', '        Object.keys(this.cache).forEach((k) => { if (!want.has(k)) delete this.cache[k]; });',
     '        Object.keys(this.cache).forEach((k) => { if (k !== planKey(this.state.plan)) delete this.cache[k]; });'],
    ['the cache never evicts', '        Object.keys(this.cache).forEach((k) => { if (!want.has(k)) delete this.cache[k]; });', ''],
    ["the panel shows the day's totals, not the row's", '        if (row) { down = row.down; up = row.up; }\n', ''],
    ['the panel filters for the scope control, not the rows shown', '            if (!this._inScope(r, q.scope)) return;',
     '            if (!this._inScope(r)) return;'],
    ['the panel never says its lists cover more', '            : same ? null : `Peers and ports cover', '            : true ? null : `Peers and ports cover'],
    ['the panel notes a same-day span as different',
     '        const same = plan.start === table.start && plan.end === table.end;',
     '        const same = plan.provider === table.provider && plan.start === table.start && plan.end === table.end;'],
    ['the panel silent when no peers are kept', '        const note = plan.end <= plan.start ? `Peers and ports are only kept for ${DETAILS_DAYS} days`',
     '        const note = false ? `Peers and ports are only kept for ${DETAILS_DAYS} days`'],
    // recent ranges from the raw flow log
    ['the raw log used for ranges older than 50 hours', '    return fromS >= nowS - RAW_REACH && fromS < nowS;', '    return fromS < nowS;'],
    ['the raw log asked for a range in the future', '    return fromS >= nowS - RAW_REACH && fromS < nowS;', '    return fromS >= nowS - RAW_REACH;'],
    ['internet only read from the all-traffic columns', "    const k = scope === 'wan' ? 2 : 0;", '    const k = 0;'],
    ['devices without traffic in the scope listed', '        .filter(r => r.down + r.up > 0);', ';'],
    ['spans rounded to the nearest minute', '    const m = Math.floor(Math.max(0, seconds) / 60);', '    const m = Math.round(Math.max(0, seconds) / 60);'],
    ['a string taken for a raw answer', "                .done((r) => (r && typeof r === 'object' && !r.error && keys.every(k => r[k]) ? resolve(r)",
     '                .done((r) => (r ? resolve(r)'],
    ['a stale raw answer lands', '            if (token !== this._loadToken) return false;\n            if (resp && resp.all.from <= from) {', '            if (resp && resp.all.from <= from) {'],
    ['a failed raw read shows nothing', '            fallback = !resp;', '            return false;'],
    ["no fallback note", '        if (this.state.fallback) c.note = c.note ? `${FALLBACK_NOTE} · ${c.note}` : FALLBACK_NOTE;\n', ''],
    ['a scope switch leaves the other scope\'s rows', '            if (q.raw) { this._applyRaw(this.state.scope); break; }', '            if (q.raw) break;'],
    ['the raw caption shows the range asked for', '        return { text: `${this._dateStr(a)}  →  ${this._endStr(b)}${tail}`, note };',
     '        return { text: `${this._dateStr(q.from)}  →  ${this._endStr(q.to)}${tail}`, note };'],
    ['no note when internet only reaches past the log', '        const note = wan && a > q.from', '        const note = false && a > q.from'],
    ['no word when internet only has nothing in the log', '        if (wan && a >= b) {', '        if (false) {'],
    ['a raw load keeps the exports of earlier windows', '                this._applyRaw(scope);\n                this._pruneCache(this.state.request);\n', '                this._applyRaw(scope);\n'],
    ['a raw table reloaded on a scope switch', '            if (q.raw) { this._applyRaw(this.state.scope); break; }', '            if (false) { this._applyRaw(this.state.scope); break; }'],
    ['a raw answer landing mid-switch ends the loop', '        while (this.state.window && q && q.scope !== this.state.scope) {', '        while (this.state.window && q && !q.raw && q.scope !== this.state.scope) {'],
    ['a raw answer applied with no table on screen', '        while (this.state.window && q && q.scope !== this.state.scope) {', '        while ((this.state.window || (q && q.raw)) && q && q.scope !== this.state.scope) {'],
    ["the caption names the widget's own WAN, not the answer's", '(r.wan || []).join', '(this.wanDevs || []).join'],
    ['the raw panel re-read on a scope switch', '        if (!this._device || this._device.key !== key)', '        if (true)'],
    ["the raw panel's internet lists taken from all traffic", "        const k = q.scope === 'wan' ? 'inet' : 'all';", "        const k = 'all';"],
    ['no note when the raw panel covers less', '            note: d.from > q.from ? ', '            note: false ? '],
    ['the panel reads the daily details on a raw range', '        if (this.state.request && this.state.request.raw) return this._rawDetails(ip);\n', ''],
    ["the framework's reply taken for a raw answer", ' && keys.every(k => r[k]) ? resolve(r)', ' ? resolve(r)'],
    ['a device answer without its lists kept', "path.startsWith('device/') ? ['peers', 'ports'] :", "path.startsWith('device/') ? [] :"],
    ['a custom range ending later asks the raw log for the future', '            const end = Math.min(to, now);', '            const end = to;'],
    ["the raw read given ajaxCall's 5 s", 'timeout: 60000', 'timeout: 5000'],
    ["midnight read as hour 24", "hourCycle: 'h23'", "hourCycle: 'h24'"],
    ["a doubled wall time taken as the later", "    if (names(before)) return before;\n", ""],
    ["a missing wall time moved back", "    return names(after) ? after : before;", "    return after;"],
    ["yesterday as 24 hours, not the calendar day", "    return wallToEpoch(day.getUTCFullYear(), day.getUTCMonth() + 1, day.getUTCDate(), 0, 0, 0, tz);", "    return wallToEpoch(y, mo, d, 0, 0, 0, tz) - back * 86400;"],
    ["the long zone name not abbreviated", "    const words = long.split(/[\\s-]+/).filter(w => /^[A-Za-z]/.test(w));\n    if (words.length > 1) return words.map(w => w[0].toUpperCase()).join('');\n", "    const words = long.split(/[\\s-]+/).filter(w => /^[A-Za-z]/.test(w));\n"],
    ["UTC's long name abbreviated to its initials (CUT) instead of UTC",
     "    if (long === 'Coordinated Universal Time') return 'UTC';    // its initials would be CUT\n", ''],
    ["midnights in the browser's zone", "        const mid = localMidnight(s, 0, this.tz);", "        const mid = localMidnight(s, 0);"],
    ["yesterday from the browser's calendar", "            case 'yesterday': return [localMidnight(s, 1, this.tz), mid];", "            case 'yesterday': return [localMidnight(s, 1), mid];"],
    ["custom fields read in the browser's zone", "+(x[6] || 0), this.tz) : null;", "+(x[6] || 0)) : null;"],
    ["custom fields written in the browser's zone", "        const [y, mo, d, h, mi] = wallParts(ts, this.tz);", "        const [y, mo, d, h, mi] = wallParts(ts);"],
    ["captions in the browser's zone", "        const [y, mo, d, h, mi, s, dow] = wallParts(ts, this.tz);", "        const [y, mo, d, h, mi, s, dow] = wallParts(ts);"],
    ["a day's end shown as the next midnight", "        return this._dateStr(localMidnight(ts, 0, this.tz) === ts ? ts - 1 : ts);", "        return this._dateStr(ts);"],
    ["a note's span ending on the next midnight", "        if (b > a && localMidnight(b, 0, this.tz) === b) b -= 1;\n", ""],
    ["a zone Intl does not know kept", "            if (tz) new Intl.DateTimeFormat('en-US', { timeZone: tz });   // throws for a zone it does not know\n", ""],
    ["an empty zone string stored instead of the browser's",
     "            tz = (r && typeof r.timezone === 'string' ? r.timezone : undefined) || undefined;   // '' is not a zone\n",
     "            tz = r && typeof r.timezone === 'string' ? r.timezone : undefined;\n"],
    ["the zone never asked", "        await this._loadZone();\n", ""],
    ['the raw reach left at a day', 'export const RAW_REACH = 50 * 3600;', 'export const RAW_REACH = DAY;'],
    ['a short raw answer shown as if whole', '            if (resp && resp.all.from <= from) {', '            if (resp) {'],
    ['a short raw answer called a failure', '            fallback = !resp;', '            fallback = true;'],
    ["the caption starts where the plan did, before any data", "        const start = this.state.first > p.start ? this.state.first : p.start;", "        const start = p.start;"],
    ["a false 'no records before' note when the data starts exactly at the plan",
     "        if (start > p.start) {", "        if (this.state.first != null) {"],
    ["no word that NetFlow began later", "            const none = `NetFlow has no records before ${this._dayTime(start)}`;\n            note = note ? `${note} · ${none}` : none;\n", ""],
    ["an empty export shown as a span", "        if (this.state.first === null) {", "        if (false) {"],
    ["bucket starts read with the offset of their own day", " / 1000 - offsetAt(nowS, tz) : null;", " / 1000 - offsetAt(Date.UTC(+x[1], +x[2] - 1, +x[3], +x[4], +x[5], +x[6]) / 1000, tz) : null;"],
    ["the newest bucket taken for the oldest", "dated.reduce((a, b) => Math.min(a, b))", "dated.reduce((a, b) => Math.max(a, b))"],
    ["with the zone unknown, a bucket's start is read with the browser's offset anyway",
     'start: this.tz === undefined ? null : exportStart(c[ix.start_time], now, this.tz)',
     'start: exportStart(c[ix.start_time], now, this.tz)'],
    // the Live detail panel resizes the widget when it appears or grows
    ['Live refits only when the row count changes', '        const shape = `${rows.length}|${lines}`;',
     '        const shape = `${rows.length}`;'],
    ['Live refits on every tick', '        if (shape !== l.shape) { l.shape = shape; this._fitHeight(); }',
     '        if (true) { l.shape = shape; this._fitHeight(); }'],
    ['the placeholder collides with a same-sized real panel',
     "$d.html('<small class=\"text-muted\">Measuring\\u2026</small>'); return -2; }",
     "$d.html('<small class=\"text-muted\">Measuring\\u2026</small>'); return 1; }"],
];

let survivors = 0;
for (const [name, from, to] of mutants) {
    const count = source.split(from).length - 1;
    if (count !== 1) { console.log(`BROKEN MUTANT ${name}: anchor found ${count} times`); process.exit(2); }
    const dir = mkdtempSync(join(tmpdir(), 'tdmut-'));
    mkdirSync(join(dir, 'src/opnsense/www/js/widgets'), { recursive: true });
    mkdirSync(join(dir, 'tests'));
    writeFileSync(join(dir, widget), source.replace(from, to));
    for (const t of TESTS) copyFileSync(join(root, t), join(dir, t));
    // a mutant that leaves a timer running keeps node alive: a hang counts as caught
    const run = spawnSync(process.execPath, ['--test', ...TESTS],
                          { cwd: dir, encoding: 'utf8', timeout: 20000 });
    const killed = run.status !== 0;
    console.log(`${killed ? 'killed  ' : 'SURVIVED'} ${name}${run.status === null ? ' (hung)' : ''}`);
    if (!killed) survivors++;
}
process.exit(survivors ? 1 : 0);
